apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apps-oom-and-trace
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: deploy/argocd/apps # deploys oom and trace apps 
    repoURL: 'https://github.com/EHSchmitt4395/grafana-argo.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
