apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-demo
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom-demo
  template:
    metadata:
      labels:
        app: oom-demo
    spec:
      containers:
      - name: memory-hog
        image: polinux/stress
        command: ["/usr/local/bin/stress"]
        args:
          - "--vm"
          - "1"
          - "--vm-bytes"
          - "500M"  # Attempt to consume 500 MB of memory
          - "--vm-hang"
          - "1"
        resources:
          limits:
            memory: "100Mi"  # Set a low memory limit
          requests:
            memory: "50Mi"
